# Generated by Django 5.1.4 on 2025-04-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code/identifier for the Initial (e.g., 'JDS')", max_length=10, unique=True)),
                ('full_name', models.CharField(blank=True, help_text='Optional full name associated with the initial', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Mark if this initial is currently active')),
            ],
            options={
                'verbose_name': 'Initial',
                'verbose_name_plural': 'Initials',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DutyHourLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(choices=[('Solo', 'Solo'), ('OJT', 'OJT'), ('Assessment', 'Assessment')], max_length=20, verbose_name='Operation Type')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('finish_time', models.TimeField(verbose_name='Finish Time')),
                ('rating', models.CharField(choices=[('ADC', 'Aerodrome Control (ADC)'), ('APP', 'Approach Control Procedural (APP)'), ('APS', 'Approach Control Surveillance (APS)'), ('ATCA', 'Area Control Procedural (ATCA)')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duty_hour_log.initial', verbose_name='Initial')),
            ],
            options={
                'verbose_name': 'Duty Hour Log',
                'verbose_name_plural': 'Duty Hour Logs',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
