# Generated by Django 5.1.4 on 2025-04-20 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_hour_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyhourlog',
            name='examiner',
            field=models.ForeignKey(blank=True, help_text='Select if Operation Type is Assessment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_examiner', to='duty_hour_log.initial', verbose_name='Examiner/Assessor'),
        ),
        migrations.AddField(
            model_name='dutyhourlog',
            name='ojti',
            field=models.ForeignKey(blank=True, help_text='Select if Operation Type is OJT or Assessment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_ojti', to='duty_hour_log.initial', verbose_name='OJTI'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_primary', to='duty_hour_log.initial', verbose_name='Initial (Controller/Student)'),
        ),
    ]
