# Generated by Django 5.1.4 on 2025-04-20 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_hour_log', '0002_dutyhourlog_examiner_dutyhourlog_ojti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyhourlog',
            name='trainee',
            field=models.ForeignKey(blank=True, help_text='Select if Operation Type is OJT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_trainee', to='duty_hour_log.initial', verbose_name='Trainee'),
        ),
    ]
