# Generated by Django 5.1.4 on 2025-04-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_hour_log', '0003_dutyhourlog_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyhourlog',
            name='examiner',
            field=models.ForeignKey(blank=True, help_text='Select for Assessment operations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_examiner', to='duty_hour_log.initial', verbose_name='Examiner/Assessor'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_primary', to='duty_hour_log.initial', verbose_name='Initial (Controller)'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='ojti',
            field=models.ForeignKey(blank=True, help_text='Select for OJT operations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_ojti', to='duty_hour_log.initial', verbose_name='OJTI'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='op',
            field=models.CharField(choices=[('', '---------'), ('Solo', 'Solo'), ('OJT', 'OJT'), ('Assessment', 'Assessment')], max_length=20, verbose_name='Operation Type'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='trainee',
            field=models.ForeignKey(blank=True, help_text='Select for OJT or Assessment operations.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duty_logs_as_trainee', to='duty_hour_log.initial', verbose_name='Trainee'),
        ),
    ]
