# Generated by Django 5.1.4 on 2025-04-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_hour_log', '0004_alter_dutyhourlog_examiner_alter_dutyhourlog_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyhourlog',
            name='rating',
            field=models.CharField(choices=[('ADC', ''), ('APP', ''), ('APS', ''), ('ATCA', '')], max_length=10),
        ),
    ]
