# Generated by Django 5.1.4 on 2025-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_hour_log', '0006_alter_dutyhourlog_op_alter_dutyhourlog_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyhourlog',
            name='duration',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='op',
            field=models.CharField(choices=[('', '---------'), ('Solo', 'Solo'), ('OJT', 'OJT'), ('Assessment', 'Assessment')], max_length=20, verbose_name='Operation Type'),
        ),
        migrations.AlterField(
            model_name='dutyhourlog',
            name='rating',
            field=models.CharField(choices=[('ADC', 'ADC'), ('APP', 'APP'), ('APS', 'APS'), ('ATCA', 'ATCA')], max_length=10),
        ),
    ]
