# Generated by Django 5.1.4 on 2025-04-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty_hour_log', '0008_remove_dutyhourlog_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutyhourlog',
            name='finish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Finish Time'),
        ),
    ]
